version: "3"
services:
  nginx:
    volumes:
      - ./config/nginx/development.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"

  cfml:
    environment:
      PORT: 80
      SSL_PORT: 443
      BOX_SERVER_PROFILE: development
      CFCONFIG_ADMINPASSWORD: defaultpass
    volumes:
      - "./app:/app"
  
  mysql:
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: defaultpass
  
  mailslurper:
    container_name: mailslurper_cfml_application_template
    image: marcopas/docker-mailslurper
    ports:
      - "127.0.0.1:2500:2500"
      - "127.0.0.1:9000:8080"
      - "127.0.0.1:8085:8085"
    networks:
      - frontend
      - backend
    restart: always
